/**
 * File generated by Magnet rest2mobile 1.1 - Dec 15, 2015 12:47:13 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ort.num172159_180968.fut5.model.beans.*;

public class StatisticsTestFactory extends ControllerFactory<StatisticsTest> {
  public StatisticsTestFactory(MagnetMobileClient magnetClient) {
    super(StatisticsTest.class, StatisticsTestSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller StatisticsTest
  public static class StatisticsTestSchemaFactory extends AbstractControllerSchemaFactory {
    private static StatisticsTestSchemaFactory __instance;

    public static synchronized StatisticsTestSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new StatisticsTestSchemaFactory();
      }

      return __instance;
    }

    private StatisticsTestSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getPlayerStatistics
      JMethod method1 = addMethod("getPlayerStatistics",
        "Fut5-war/webservice/getPlayerStatistics",
        "GET",
        PlayerStatisticsResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://192.168.1.106:8080");
      method1.addParam("username",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
