/**
 * File generated by Magnet rest2mobile 1.1 - Dec 15, 2015 12:47:13 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;

public interface StatisticsTest {

  /**
   * Generated from URL GET http://192.168.1.106:8080/Fut5-war/webservice/getPlayerStatistics?username=juan
   * GET Fut5-war/webservice/getPlayerStatistics
   * @param username  style:QUERY
   * @param listener
   * @return PlayerStatisticsResult
   */
  Call<PlayerStatisticsResult> getPlayerStatistics(
     String username,
     StateChangedListener listener
  );


}
