/**
 * File generated by Magnet rest2mobile 1.1 - Nov 26, 2015 7:48:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "notificationId" : 152,
  "notificationType" : "NEWMATCH",
  "notificationText" : "Youhavebeeninvitedbyjuanma,toplayagamein:0Stress",
  "notificationDate" : 1445890320000
}

 */

public class NotificationsResult {

  
  private Long notificationDate;

  
  private Integer notificationId;

  
  private String notificationText;

  
  private String notificationType;

  public Long getNotificationDate() {
    return notificationDate;
  }
  public Integer getNotificationId() {
    return notificationId;
  }
  public String getNotificationText() {
    return notificationText;
  }
  public String getNotificationType() {
    return notificationType;
  }

  /**
  * Builder for NotificationsResult
  **/
  public static class NotificationsResultBuilder {
    private NotificationsResult toBuild = new NotificationsResult();

    public NotificationsResultBuilder() {
    }

    public NotificationsResult build() {
      return toBuild;
    }

    public NotificationsResultBuilder notificationDate(Long value) {
      toBuild.notificationDate = value;
      return this;
    }
    public NotificationsResultBuilder notificationId(Integer value) {
      toBuild.notificationId = value;
      return this;
    }
    public NotificationsResultBuilder notificationText(String value) {
      toBuild.notificationText = value;
      return this;
    }
    public NotificationsResultBuilder notificationType(String value) {
      toBuild.notificationType = value;
      return this;
    }
  }
}
