/**
 * File generated by Magnet rest2mobile 1.1 - Oct 12, 2015 11:30:44 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "fieldId" : 1,
  "fieldName" : "0Stress",
  "fieldLat" : -34.8736473,
  "fieldLon" : -56.1775762
}

 */

public class FieldsResult {

  
  private Integer fieldId;

  
  private Double fieldLat;

  
  private Double fieldLon;

  
  private String fieldName;

  public Integer getFieldId() {
    return fieldId;
  }
  public Double getFieldLat() {
    return fieldLat;
  }
  public Double getFieldLon() {
    return fieldLon;
  }
  public String getFieldName() {
    return fieldName;
  }

  /**
  * Builder for FieldsResult
  **/
  public static class FieldsResultBuilder {
    private FieldsResult toBuild = new FieldsResult();

    public FieldsResultBuilder() {
    }

    public FieldsResult build() {
      return toBuild;
    }

    public FieldsResultBuilder fieldId(Integer value) {
      toBuild.fieldId = value;
      return this;
    }
    public FieldsResultBuilder fieldLat(Double value) {
      toBuild.fieldLat = value;
      return this;
    }
    public FieldsResultBuilder fieldLon(Double value) {
      toBuild.fieldLon = value;
      return this;
    }
    public FieldsResultBuilder fieldName(String value) {
      toBuild.fieldName = value;
      return this;
    }
  }
}
