/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "pod" : "d"
}

 */

public class ListSys {

  
  private String pod;

  public String getPod() {
    return pod;
  }

  /**
  * Builder for ListSys
  **/
  public static class ListSysBuilder {
    private ListSys toBuild = new ListSys();

    public ListSysBuilder() {
    }

    public ListSys build() {
      return toBuild;
    }

    public ListSysBuilder pod(String value) {
      toBuild.pod = value;
      return this;
    }
  }
}
