/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 7:57:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "fieldId" : 20,
  "fieldName" : "CampusPrado",
  "fieldLat" : -34.865167,
  "fieldLon" : -56.189876
}

 */

public class MatchField {

  
  private Integer fieldId;

  
  private Double fieldLat;

  
  private Double fieldLon;

  
  private String fieldName;

  public Integer getFieldId() {
    return fieldId;
  }
  public Double getFieldLat() {
    return fieldLat;
  }
  public Double getFieldLon() {
    return fieldLon;
  }
  public String getFieldName() {
    return fieldName;
  }

  /**
  * Builder for MatchField
  **/
  public static class MatchFieldBuilder {
    private MatchField toBuild = new MatchField();

    public MatchFieldBuilder() {
    }

    public MatchField build() {
      return toBuild;
    }

    public MatchFieldBuilder fieldId(Integer value) {
      toBuild.fieldId = value;
      return this;
    }
    public MatchFieldBuilder fieldLat(Double value) {
      toBuild.fieldLat = value;
      return this;
    }
    public MatchFieldBuilder fieldLon(Double value) {
      toBuild.fieldLon = value;
      return this;
    }
    public MatchFieldBuilder fieldName(String value) {
      toBuild.fieldName = value;
      return this;
    }
  }
}
