/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "3h" : 0.04
}

 */

public class Rain {

  
@com.google.gson.annotations.SerializedName("3h")
  private Double property3h;

  public Double getProperty3h() {
    return property3h;
  }

  /**
  * Builder for Rain
  **/
  public static class RainBuilder {
    private Rain toBuild = new Rain();

    public RainBuilder() {
    }

    public Rain build() {
      return toBuild;
    }

    public RainBuilder property3h(Double value) {
      toBuild.property3h = value;
      return this;
    }
  }
}
