/**
 * File generated by Magnet rest2mobile 1.1 - Dec 13, 2015 1:36:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "matchStadisticsId" : 201,
  "team1Goals" : 1,
  "team2Goals" : 2
}

 */

public class SaveMatchGoalsResult {

  
  private Integer matchStadisticsId;

  
  private Integer team1Goals;

  
  private Integer team2Goals;

  public Integer getMatchStadisticsId() {
    return matchStadisticsId;
  }
  public Integer getTeam1Goals() {
    return team1Goals;
  }
  public Integer getTeam2Goals() {
    return team2Goals;
  }

  /**
  * Builder for SaveMatchGoalsResult
  **/
  public static class SaveMatchGoalsResultBuilder {
    private SaveMatchGoalsResult toBuild = new SaveMatchGoalsResult();

    public SaveMatchGoalsResultBuilder() {
    }

    public SaveMatchGoalsResult build() {
      return toBuild;
    }

    public SaveMatchGoalsResultBuilder matchStadisticsId(Integer value) {
      toBuild.matchStadisticsId = value;
      return this;
    }
    public SaveMatchGoalsResultBuilder team1Goals(Integer value) {
      toBuild.team1Goals = value;
      return this;
    }
    public SaveMatchGoalsResultBuilder team2Goals(Integer value) {
      toBuild.team2Goals = value;
      return this;
    }
  }
}
