/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "population" : 0
}

 */

public class Sys {

  
  private Integer population;

  public Integer getPopulation() {
    return population;
  }

  /**
  * Builder for Sys
  **/
  public static class SysBuilder {
    private Sys toBuild = new Sys();

    public SysBuilder() {
    }

    public Sys build() {
      return toBuild;
    }

    public SysBuilder population(Integer value) {
      toBuild.population = value;
      return this;
    }
  }
}
