/**
 * File generated by Magnet rest2mobile 1.1 - Nov 20, 2015 7:41:04 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;

public class UsersWithImagesResult {

  
  private String email;

  
  private String firstName;

  
  private String lastName;

  
  private String photo;

  
  private Integer userId;

  
  private String username;

  public String getEmail() {
    return email;
  }
  public String getFirstName() {
    return firstName;
  }
  public String getLastName() {
    return lastName;
  }
  public String getPhoto() {
    return photo;
  }
  public Integer getUserId() {
    return userId;
  }
  public String getUsername() {
    return username;
  }

  /**
  * Builder for UsersWithImagesResult
  **/
  public static class UsersWithImagesResultBuilder {
    private UsersWithImagesResult toBuild = new UsersWithImagesResult();

    public UsersWithImagesResultBuilder() {
    }

    public UsersWithImagesResult build() {
      return toBuild;
    }

    public UsersWithImagesResultBuilder email(String value) {
      toBuild.email = value;
      return this;
    }
    public UsersWithImagesResultBuilder firstName(String value) {
      toBuild.firstName = value;
      return this;
    }
    public UsersWithImagesResultBuilder lastName(String value) {
      toBuild.lastName = value;
      return this;
    }
    public UsersWithImagesResultBuilder photo(String value) {
      toBuild.photo = value;
      return this;
    }
    public UsersWithImagesResultBuilder userId(Integer value) {
      toBuild.userId = value;
      return this;
    }
    public UsersWithImagesResultBuilder username(String value) {
      toBuild.username = value;
      return this;
    }
  }
}
