/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "city" : {
    "id" : 3441575,
    "name" : "Montevideo",
    "coord" : {
      "lon" : -56.167351,
      "lat" : -34.833462
    },
    "country" : "UY",
    "population" : 0,
    "sys" : {
      "population" : 0
    }
  },
  "cod" : "200",
  "message" : 0.006,
  "cnt" : 40,
  "list" : [ {
    "dt" : 1448658000,
    "main" : {
        ...

 */

public class WeatherResult {

  
  private City city;

  
  private Integer cnt;

  
  private String cod;

  
  private List<ListWeather> list;

  
  private Double message;

  public City getCity() {
    return city;
  }
  public Integer getCnt() {
    return cnt;
  }
  public String getCod() {
    return cod;
  }
  public List<ListWeather> getList() {
    return list;
  }
  public Double getMessage() {
    return message;
  }

  /**
  * Builder for WeatherResult
  **/
  public static class WeatherResultBuilder {
    private WeatherResult toBuild = new WeatherResult();

    public WeatherResultBuilder() {
    }

    public WeatherResult build() {
      return toBuild;
    }

    public WeatherResultBuilder city(City value) {
      toBuild.city = value;
      return this;
    }
    public WeatherResultBuilder cnt(Integer value) {
      toBuild.cnt = value;
      return this;
    }
    public WeatherResultBuilder cod(String value) {
      toBuild.cod = value;
      return this;
    }
    public WeatherResultBuilder list(List<ListWeather> value) {
      toBuild.list = value;
      return this;
    }
    public WeatherResultBuilder message(Double value) {
      toBuild.message = value;
      return this;
    }
  }
}
