/**
 * File generated by Magnet rest2mobile 1.1 - Oct 12, 2015 11:30:44 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;
import java.util.List;

public interface Fields {

  /**
   * Generated from URL GET http://192.168.1.106:8080/Fut5-war/webservice/getFields
   * GET Fut5-war/webservice/getFields
   * @param listener
   * @return List<FieldsResult>
   */
  Call<List<FieldsResult>> getFields(StateChangedListener listener);
}
