/**
 * File generated by Magnet rest2mobile 1.1 - Dec 13, 2015 1:36:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ort.num172159_180968.fut5.model.beans.*;

public class StatisticFactory extends ControllerFactory<Statistic> {
  public StatisticFactory(MagnetMobileClient magnetClient) {
    super(Statistic.class, StatisticSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller Statistic
  public static class StatisticSchemaFactory extends AbstractControllerSchemaFactory {
    private static StatisticSchemaFactory __instance;

    public static synchronized StatisticSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new StatisticSchemaFactory();
      }

      return __instance;
    }

    private StatisticSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getMatchGoals
      JMethod method1 = addMethod("getMatchGoals",
        "Fut5-war/webservice/getMatchStadistics",
        "GET",
        MatchGoalsResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://" + Value.ip + ":8080");
      method1.addParam("idMatch",
              "QUERY",
              String.class,
              null,
              "",
              true);

      //controller schema for controller method saveMatchGoals
      JMethod method2 = addMethod("saveMatchGoals",
        "Fut5-war/webservice/addMatchStadistics",
        "POST",
        SaveMatchGoalsResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method2.setBaseUrl("http://" + Value.ip + ":8080");
      method2.addParam("idMatch",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method2.addParam("localGoals",
              "QUERY",
              String.class,
              null,
              "",
              true);
      method2.addParam("visitorGoals",
        "QUERY",
        String.class,
        null,
        "",
        true);

      JMethod method3 = addMethod("getPlayerStatistics",
              "Fut5-war/webservice/getPlayerStatistics",
              "GET",
              PlayerStatisticsResult.class,
              null,
              null,
              Arrays.asList("application/json"));
      method3.setBaseUrl("http://" + Value.ip + ":8080");
      method3.addParam("username",
              "QUERY",
              String.class,
              null,
              "",
              true);
    }

  }

}
