/**
 * File generated by Magnet rest2mobile 1.1 - Nov 26, 2015 7:48:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;
import java.util.List;

public interface UserNotification {

  /**
   * Generated from URL GET http://localhost:8080/Fut5-war/webservice/getNotifications?username=juanma
   * GET Fut5-war/webservice/getNotifications
   * @param username  style:QUERY
   * @param listener
   * @return List<NotificationsResult>
   */
  Call<List<NotificationsResult>> getNotifications(
     String username,
     StateChangedListener listener
  );


}
