/**
 * File generated by Magnet rest2mobile 1.1 - Oct 17, 2015 9:16:14 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;


public interface UserLogIn {

  /**
   * Generated from URL GET http://localhost:8080/Fut5-war/webservice/logIn?username=juan&password=pepe
   * GET Fut5-war/webservice/logIn
   * @param username  style:QUERY
   * @param password  style:QUERY
   * @param listener
   * @return String
   */
  Call<String> logIn(
     String username,
     String password,
     StateChangedListener listener
  );


}
