/**
 * File generated by Magnet rest2mobile 1.1 - Oct 17, 2015 9:16:14 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Arrays;

import static com.ort.num172159_180968.fut5.R.string.backend_ip;


public class UserLogInFactory extends ControllerFactory<UserLogIn> {
  public UserLogInFactory(MagnetMobileClient magnetClient) {
    super(UserLogIn.class, UserLogInSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller UserLogIn
  public static class UserLogInSchemaFactory extends AbstractControllerSchemaFactory {
    private static UserLogInSchemaFactory __instance;

    public static synchronized UserLogInSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new UserLogInSchemaFactory();
      }

      return __instance;
    }

    private UserLogInSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method logIn
      JMethod method1 = addMethod("logIn",
        "Fut5-war/webservice/logIn",
        "GET",
        String.class,
        null,
        null,
        Arrays.asList("text/plain"));
      method1.setBaseUrl("http://" + "192.168.1.106" + ":8080");
      method1.addParam("username",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("password",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
