/**
 * File generated by Magnet rest2mobile 1.1 - Oct 14, 2015 9:00:34 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;

import java.util.List;

public interface User {

  /**
   * Generated from URL POST http://localhost:8080/Fut5-war/webservice/addUser?username=juan&password=juan&firstName=Juan&lastName=Gallo&email=juan_gallo1%40hotmail.com&url=a
   * POST Fut5-war/webservice/addUser
   * @param username  style:QUERY
   * @param password  style:QUERY
   * @param firstName  style:QUERY
   * @param lastName  style:QUERY
   * @param email  style:QUERY
   * @param url  style:QUERY
   * @param listener
   * @return UserResult
   */
  Call<UserResult> addUser(
     String username,
     String password,
     String firstName,
     String lastName,
     String email,
     String url,
     StateChangedListener listener
  );

    Call<List<UserResult>> getUsers(
            String username,
            StateChangedListener listener
    );

    Call<String> getUserImage(
            String username,
            StateChangedListener listener
    );

    Call<String> addUserImage(
            String username,
            AddUserImageRequest body,
            StateChangedListener listener
    );

    Call<List<UsersWithImagesResult>> getUsersWithImages(String username, StateChangedListener listener);

    Call<String> updateUser(
            String userId,
            String username,
            String password,
            String firstName,
            String lastName,
            String email,
            UpdateUserRequest body,
            StateChangedListener listener
    );

    Call<String> getNeedsUserReload(
            String username,
            StateChangedListener listener
    );
}
