/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;

public interface Weather {

  /**
   * Generated from URL GET http://api.openweathermap.org/data/2.5/forecast?id=3441575&APPID=31395b2bf7f4b409f44676dd0ba53c5b&units=metric
   * GET data/2.5/forecast
   * @param id  style:QUERY
   * @param aPPID (original name : APPID) style:QUERY
   * @param units  style:QUERY
   * @param listener
   * @return WeatherResult
   */
  Call<WeatherResult> getWeather(
     String id,
     String aPPID,
     String units,
     StateChangedListener listener
  );


}
