/**
 * File generated by Magnet rest2mobile 1.1 - Dec 15, 2015 12:47:13 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "won" : 92,
  "draw" : 7,
  "loss" : 70,
  "red" : 5,
  "yellow" : 8,
  "panna" : 16,
  "goal" : 309,
  "championship" : 1
}

 */

public class PlayerStatisticsResult {

  
  private Integer championship;

  
  private Integer draw;

  
  private Integer goal;

  
  private Integer loss;

  
  private Integer panna;

  
  private Integer red;

  
  private Integer won;

  
  private Integer yellow;

  public Integer getChampionship() {
    return championship;
  }
  public Integer getDraw() {
    return draw;
  }
  public Integer getGoal() {
    return goal;
  }
  public Integer getLoss() {
    return loss;
  }
  public Integer getPanna() {
    return panna;
  }
  public Integer getRed() {
    return red;
  }
  public Integer getWon() {
    return won;
  }
  public Integer getYellow() {
    return yellow;
  }

  /**
  * Builder for PlayerStatisticsResult
  **/
  public static class PlayerStatisticsResultBuilder {
    private PlayerStatisticsResult toBuild = new PlayerStatisticsResult();

    public PlayerStatisticsResultBuilder() {
    }

    public PlayerStatisticsResult build() {
      return toBuild;
    }

    public PlayerStatisticsResultBuilder championship(Integer value) {
      toBuild.championship = value;
      return this;
    }
    public PlayerStatisticsResultBuilder draw(Integer value) {
      toBuild.draw = value;
      return this;
    }
    public PlayerStatisticsResultBuilder goal(Integer value) {
      toBuild.goal = value;
      return this;
    }
    public PlayerStatisticsResultBuilder loss(Integer value) {
      toBuild.loss = value;
      return this;
    }
    public PlayerStatisticsResultBuilder panna(Integer value) {
      toBuild.panna = value;
      return this;
    }
    public PlayerStatisticsResultBuilder red(Integer value) {
      toBuild.red = value;
      return this;
    }
    public PlayerStatisticsResultBuilder won(Integer value) {
      toBuild.won = value;
      return this;
    }
    public PlayerStatisticsResultBuilder yellow(Integer value) {
      toBuild.yellow = value;
      return this;
    }
  }
}
