/**
 * File generated by Magnet rest2mobile 1.1 - Nov 25, 2015 12:58:57 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "local" : [ 10000, 10001, 10002, 10003, 10004 ],
  "visitor" : [ 10005, 10006, 10007, 10008, 10009 ]
}

 */

public class AddMatchRequest {

  
  private List<java.lang.Integer> local;

  
  private List<java.lang.Integer> visitor;

  public List<java.lang.Integer> getLocal() {
    return local;
  }
  public List<java.lang.Integer> getVisitor() {
    return visitor;
  }

  /**
  * Builder for AddMatchRequest
  **/
  public static class AddMatchRequestBuilder {
    private AddMatchRequest toBuild = new AddMatchRequest();

    public AddMatchRequestBuilder() {
    }

    public AddMatchRequest build() {
      return toBuild;
    }

    public AddMatchRequestBuilder local(List<java.lang.Integer> value) {
      toBuild.local = value;
      return this;
    }
    public AddMatchRequestBuilder visitor(List<java.lang.Integer> value) {
      toBuild.visitor = value;
      return this;
    }
  }
}
