/**
 * File generated by Magnet rest2mobile 1.1 - Nov 25, 2015 12:58:57 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "matchId" : 53,
  "teams" : [ {
    "userId" : 10000,
    "username" : "a",
    "password" : "a",
    "firstName" : "a",
    "lastName" : "a",
    "email" : "a",
    "userNotifications" : [ ],
    "needsFieldReload" : false,
    "needsUserReload" : false
  }, {
    "userId" : 10001,
    "username" : "b",
    "password" : "b",
    "firstName" : "b",
    "lastName" : "b",
    "email" : "b",
    "userNotifications" : [ ],
      ...

 */

public class AddMatchResult {

  
  private CreatedByUser createdByUser;

  
  private String matchDate;

  
  private MatchField matchField;

  
  private Integer matchId;

  
  private List<Team> teams;

  public CreatedByUser getCreatedByUser() {
    return createdByUser;
  }
  public String getMatchDate() {
    return matchDate;
  }
  public MatchField getMatchField() {
    return matchField;
  }
  public Integer getMatchId() {
    return matchId;
  }
  public List<Team> getTeams() {
    return teams;
  }

  /**
  * Builder for AddMatchResult
  **/
  public static class AddMatchResultBuilder {
    private AddMatchResult toBuild = new AddMatchResult();

    public AddMatchResultBuilder() {
    }

    public AddMatchResult build() {
      return toBuild;
    }

    public AddMatchResultBuilder createdByUser(CreatedByUser value) {
      toBuild.createdByUser = value;
      return this;
    }
    public AddMatchResultBuilder matchDate(String value) {
      toBuild.matchDate = value;
      return this;
    }
    public AddMatchResultBuilder matchField(MatchField value) {
      toBuild.matchField = value;
      return this;
    }
    public AddMatchResultBuilder matchId(Integer value) {
      toBuild.matchId = value;
      return this;
    }
    public AddMatchResultBuilder teams(List<Team> value) {
      toBuild.teams = value;
      return this;
    }
  }
}
