/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 7:57:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "matchId" : 51,
  "teams" : [ {
    "userId" : 1,
    "username" : "juanma",
    "password" : "juanma",
    "firstName" : "JuanMartin",
    "lastName" : "Gallo",
    "email" : "juan_gallo1@hotmail.com",
    "userNotifications" : [ {
      "notificationId" : 52,
      "notificationType" : "NEWMATCH",
      "notificationText" : "Youhavebeeninvitedbynull,toplayagamein:CampusPrado",
      "notificationDate" : 1448319600000
    }, {
      "notificationId" : 63,
      "notificationType" : "NEWMATCH",
      "notificationText" : "Youhavebeeninvitedbymika,toplayagamein:CampusPrado",
      "notificationDate" : 1448319600000
    } ],
      ...

 */

public class MatchesResult {

  
  private CreatedByUser createdByUser;

  
  private Long matchDate;

  
  private MatchField matchField;

  
  private Integer matchId;

  
  private List<Team> teams;

  public CreatedByUser getCreatedByUser() {
    return createdByUser;
  }
  public Long getMatchDate() {
    return matchDate;
  }
  public MatchField getMatchField() {
    return matchField;
  }
  public Integer getMatchId() {
    return matchId;
  }
  public List<Team> getTeams() {
    return teams;
  }

  /**
  * Builder for MatchesResult
  **/
  public static class MatchesResultBuilder {
    private MatchesResult toBuild = new MatchesResult();

    public MatchesResultBuilder() {
    }

    public MatchesResult build() {
      return toBuild;
    }

    public MatchesResultBuilder createdByUser(CreatedByUser value) {
      toBuild.createdByUser = value;
      return this;
    }
    public MatchesResultBuilder matchDate(Long value) {
      toBuild.matchDate = value;
      return this;
    }
    public MatchesResultBuilder matchField(MatchField value) {
      toBuild.matchField = value;
      return this;
    }
    public MatchesResultBuilder matchId(Integer value) {
      toBuild.matchId = value;
      return this;
    }
    public MatchesResultBuilder teams(List<Team> value) {
      toBuild.teams = value;
      return this;
    }
  }
}
