/**
 * File generated by Magnet rest2mobile 1.1 - Dec 13, 2015 1:36:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "userId" : 4,
  "username" : "mika",
  "password" : "mika",
  "firstName" : "Miakel",
  "lastName" : "Lijtenstein",
  "email" : "mikalij@hotmail.com",
  "userNotifications" : [ {
    "notificationId" : 55,
    "notificationType" : "NEWMATCH",
    "notificationText" : "Youhavebeeninvitedbynull,toplayagamein:CampusPrado",
    "notificationDate" : 1448319600000
  }, {
    "notificationId" : 66,
    "notificationType" : "NEWMATCH",
    "notificationText" : "Youhavebeeninvitedbymika,toplayagamein:CampusPrado",
    "notificationDate" : 1448319600000
  }, {
    "notificationId" : 105,
    "notificationType" : "NEWMATCH",
      ...

 */

public class CreatedByUser {

  
  private String email;

  
  private String firstName;

  
  private String lastName;

  
  private Boolean needsFieldReload;

  
  private Boolean needsUserReload;

  
  private String password;

  
  private Integer userId;

  
  private List<UserNotification> userNotifications;

  
  private String username;

  public String getEmail() {
    return email;
  }
  public String getFirstName() {
    return firstName;
  }
  public String getLastName() {
    return lastName;
  }
  public Boolean getNeedsFieldReload() {
    return needsFieldReload;
  }
  public Boolean getNeedsUserReload() {
    return needsUserReload;
  }
  public String getPassword() {
    return password;
  }
  public Integer getUserId() {
    return userId;
  }
  public List<UserNotification> getUserNotifications() {
    return userNotifications;
  }
  public String getUsername() {
    return username;
  }

  /**
  * Builder for CreatedByUser
  **/
  public static class CreatedByUserBuilder {
    private CreatedByUser toBuild = new CreatedByUser();

    public CreatedByUserBuilder() {
    }

    public CreatedByUser build() {
      return toBuild;
    }

    public CreatedByUserBuilder email(String value) {
      toBuild.email = value;
      return this;
    }
    public CreatedByUserBuilder firstName(String value) {
      toBuild.firstName = value;
      return this;
    }
    public CreatedByUserBuilder lastName(String value) {
      toBuild.lastName = value;
      return this;
    }
    public CreatedByUserBuilder needsFieldReload(Boolean value) {
      toBuild.needsFieldReload = value;
      return this;
    }
    public CreatedByUserBuilder needsUserReload(Boolean value) {
      toBuild.needsUserReload = value;
      return this;
    }
    public CreatedByUserBuilder password(String value) {
      toBuild.password = value;
      return this;
    }
    public CreatedByUserBuilder userId(Integer value) {
      toBuild.userId = value;
      return this;
    }
    public CreatedByUserBuilder userNotifications(List<UserNotification> value) {
      toBuild.userNotifications = value;
      return this;
    }
    public CreatedByUserBuilder username(String value) {
      toBuild.username = value;
      return this;
    }
  }
}
