/**
 * File generated by Magnet rest2mobile 1.1 - Dec 13, 2015 1:36:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "matchStadisticsId" : 151,
  "match" : {
    "matchId" : 62,
    "teams" : [ {
      "userId" : 1,
      "username" : "juanma",
      "password" : "juanma",
      "firstName" : "JuanMartin",
      "lastName" : "Gallo",
      "email" : "juan_gallo1@hotmail.com",
      "userNotifications" : [ {
        "notificationId" : 52,
        "notificationType" : "NEWMATCH",
        "notificationText" : "Youhavebeeninvitedbynull,toplayagamein:CampusPrado",
        "notificationDate" : 1448319600000
      }, {
        "notificationId" : 63,
        "notificationType" : "NEWMATCH",
        "notificationText" : "Youhavebeeninvitedbymika,toplayagamein:CampusPrado",
          ...

 */

public class MatchGoalsResult {

  
  private Match match;

  
  private Integer matchStadisticsId;

  
  private Integer team1Goals;

  
  private Integer team2Goals;

  public Match getMatch() {
    return match;
  }
  public Integer getMatchStadisticsId() {
    return matchStadisticsId;
  }
  public Integer getTeam1Goals() {
    return team1Goals;
  }
  public Integer getTeam2Goals() {
    return team2Goals;
  }

  /**
  * Builder for MatchGoalsResult
  **/
  public static class MatchGoalsResultBuilder {
    private MatchGoalsResult toBuild = new MatchGoalsResult();

    public MatchGoalsResultBuilder() {
    }

    public MatchGoalsResult build() {
      return toBuild;
    }

    public MatchGoalsResultBuilder match(Match value) {
      toBuild.match = value;
      return this;
    }
    public MatchGoalsResultBuilder matchStadisticsId(Integer value) {
      toBuild.matchStadisticsId = value;
      return this;
    }
    public MatchGoalsResultBuilder team1Goals(Integer value) {
      toBuild.team1Goals = value;
      return this;
    }
    public MatchGoalsResultBuilder team2Goals(Integer value) {
      toBuild.team2Goals = value;
      return this;
    }
  }
}
