/**
 * File generated by Magnet rest2mobile 1.1 - Oct 17, 2015 9:18:08 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;


public interface UserExists {

  /**
   * Generated from URL GET http://localhost:8080/Fut5-war/webservice/existsUser?username=juan
   * GET Fut5-war/webservice/existsUser
   * @param username  style:QUERY
   * @param listener
   * @return String
   */
  Call<String> userExists(
     String username,
     StateChangedListener listener
  );


}
