/**
 * File generated by Magnet rest2mobile 1.1 - Dec 14, 2015 12:31:05 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ort.num172159_180968.fut5.model.beans.*;

public class UserStatisticsFactory extends ControllerFactory<UserStatistics> {
  public UserStatisticsFactory(MagnetMobileClient magnetClient) {
    super(UserStatistics.class, UserStatisticsSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller UserStatistics
  public static class UserStatisticsSchemaFactory extends AbstractControllerSchemaFactory {
    private static UserStatisticsSchemaFactory __instance;

    public static synchronized UserStatisticsSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new UserStatisticsSchemaFactory();
      }

      return __instance;
    }

    private UserStatisticsSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method addMatchStadisticDetail
      JMethod method1 = addMethod("addMatchStadisticDetail",
        "Fut5-war/webservice/addMatchStadisticDetail",
        "POST",
        AddMatchStadisticDetailResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://192.168.1.6:8080");
      method1.addParam("idMatch",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("idUser",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("goals",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("yellowCard",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("redCard",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("pannas",
        "QUERY",
        String.class,
        null,
        "",
        true);

      //controller schema for controller method getMatchStadisticDetail
      JMethod method2 = addMethod("getMatchStadisticDetail",
        "Fut5-war/webservice/getMatchStadisticDetail",
        "GET",
        MatchStadisticDetailResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method2.setBaseUrl("http://192.168.1.6:8080");
      method2.addParam("idMatch",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method2.addParam("idUser",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
