/**
 * File generated by Magnet rest2mobile 1.1 - Dec 14, 2015 12:31:05 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;

public interface UserStatistics {

  /**
   * Generated from URL POST http://192.168.1.6:8080/Fut5-war/webservice/addMatchStadisticDetail?idMatch=303&idUser=1&goals=1&yellowCard=true&redCard=false&pannas=2
   * POST Fut5-war/webservice/addMatchStadisticDetail
   * @param idMatch  style:QUERY
   * @param idUser  style:QUERY
   * @param goals  style:QUERY
   * @param yellowCard  style:QUERY
   * @param redCard  style:QUERY
   * @param pannas  style:QUERY
   * @param listener
   * @return AddMatchStadisticDetailResult
   */
  Call<AddMatchStadisticDetailResult> addMatchStadisticDetail(
     String idMatch,
     String idUser,
     String goals,
     String yellowCard,
     String redCard,
     String pannas,
     StateChangedListener listener
  );



  /**
   * Generated from URL GET http://192.168.1.6:8080/Fut5-war/webservice/getMatchStadisticDetail?idMatch=303&idUser=1
   * GET Fut5-war/webservice/getMatchStadisticDetail
   * @param idMatch  style:QUERY
   * @param idUser  style:QUERY
   * @param listener
   * @return MatchStadisticDetailResult
   */
  Call<MatchStadisticDetailResult> getMatchStadisticDetail(
     String idMatch,
     String idUser,
     StateChangedListener listener
  );


}
