/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ort.num172159_180968.fut5.model.beans.*;

public class WeatherFactory extends ControllerFactory<Weather> {
  public WeatherFactory(MagnetMobileClient magnetClient) {
    super(Weather.class, WeatherSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller Weather
  public static class WeatherSchemaFactory extends AbstractControllerSchemaFactory {
    private static WeatherSchemaFactory __instance;

    public static synchronized WeatherSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new WeatherSchemaFactory();
      }

      return __instance;
    }

    private WeatherSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getWeather
      JMethod method1 = addMethod("getWeather",
        "data/2.5/forecast",
        "GET",
        WeatherResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://api.openweathermap.org");
      method1.addParam("id",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("APPID",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("units",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
