/**
 * File generated by Magnet rest2mobile 1.1 - Dec 14, 2015 12:31:05 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "matchStadisticsDetailId" : 451,
  "matchStadistics" : {
    "matchStadisticsId" : 363,
    "match" : {
      "matchId" : 303,
      "teams" : [ {
        "userId" : 1,
        "username" : "juanma",
        "password" : "juanma",
        "firstName" : "JuanMartin",
        "lastName" : "Gallo",
        "email" : "juan_gallo1@hotmail.com",
        "userNotifications" : [ {
          "notificationId" : 52,
          "notificationType" : "NEWMATCH",
          "notificationText" : "Youhavebeeninvitedbynull,toplayagamein:CampusPrado",
          "notificationDate" : 1448319600000
        }, {
          "notificationId" : 63,
            ...

 */

public class AddMatchStadisticDetailResult {

  
  private Integer goals;

  
  private MatchStadistics matchStadistics;

  
  private Integer matchStadisticsDetailId;

  
  private Integer pannas;

  
  private Boolean redCard;

  
  private User user;

  
  private Boolean yellowCard;

  public Integer getGoals() {
    return goals;
  }
  public MatchStadistics getMatchStadistics() {
    return matchStadistics;
  }
  public Integer getMatchStadisticsDetailId() {
    return matchStadisticsDetailId;
  }
  public Integer getPannas() {
    return pannas;
  }
  public Boolean getRedCard() {
    return redCard;
  }
  public User getUser() {
    return user;
  }
  public Boolean getYellowCard() {
    return yellowCard;
  }

  /**
  * Builder for AddMatchStadisticDetailResult
  **/
  public static class AddMatchStadisticDetailResultBuilder {
    private AddMatchStadisticDetailResult toBuild = new AddMatchStadisticDetailResult();

    public AddMatchStadisticDetailResultBuilder() {
    }

    public AddMatchStadisticDetailResult build() {
      return toBuild;
    }

    public AddMatchStadisticDetailResultBuilder goals(Integer value) {
      toBuild.goals = value;
      return this;
    }
    public AddMatchStadisticDetailResultBuilder matchStadistics(MatchStadistics value) {
      toBuild.matchStadistics = value;
      return this;
    }
    public AddMatchStadisticDetailResultBuilder matchStadisticsDetailId(Integer value) {
      toBuild.matchStadisticsDetailId = value;
      return this;
    }
    public AddMatchStadisticDetailResultBuilder pannas(Integer value) {
      toBuild.pannas = value;
      return this;
    }
    public AddMatchStadisticDetailResultBuilder redCard(Boolean value) {
      toBuild.redCard = value;
      return this;
    }
    public AddMatchStadisticDetailResultBuilder user(User value) {
      toBuild.user = value;
      return this;
    }
    public AddMatchStadisticDetailResultBuilder yellowCard(Boolean value) {
      toBuild.yellowCard = value;
      return this;
    }
  }
}
