/**
 * File generated by Magnet rest2mobile 1.1 - Dec 14, 2015 12:31:04 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "userId" : 302,
  "username" : "10156116930130472",
  "firstName" : "Mika",
  "lastName" : "Lijtenstein",
  "userNotifications" : [ {
    "notificationId" : 309,
    "notificationType" : "NEWMATCH",
    "notificationText" : "Youhavebeeninvitedby10156116930130472,toplayagamein:Albatros",
    "notificationDate" : 1449702000000
  }, {
    "notificationId" : 358,
    "notificationType" : "NEWMATCH",
    "notificationText" : "Youhavebeeninvitedby10156116930130472,toplayagamein:0Stress",
    "notificationDate" : 1451426400000
  } ],
  "needsFieldReload" : false,
  "needsUserReload" : false
}

 */

public class CreatedByUser {

  
  private String firstName;

  
  private String lastName;

  
  private Boolean needsFieldReload;

  
  private Boolean needsUserReload;

  
  private Integer userId;

  
  private List<UserNotification> userNotifications;

  
  private String username;

  public String getFirstName() {
    return firstName;
  }
  public String getLastName() {
    return lastName;
  }
  public Boolean getNeedsFieldReload() {
    return needsFieldReload;
  }
  public Boolean getNeedsUserReload() {
    return needsUserReload;
  }
  public Integer getUserId() {
    return userId;
  }
  public List<UserNotification> getUserNotifications() {
    return userNotifications;
  }
  public String getUsername() {
    return username;
  }

  /**
  * Builder for CreatedByUser
  **/
  public static class CreatedByUserBuilder {
    private CreatedByUser toBuild = new CreatedByUser();

    public CreatedByUserBuilder() {
    }

    public CreatedByUser build() {
      return toBuild;
    }

    public CreatedByUserBuilder firstName(String value) {
      toBuild.firstName = value;
      return this;
    }
    public CreatedByUserBuilder lastName(String value) {
      toBuild.lastName = value;
      return this;
    }
    public CreatedByUserBuilder needsFieldReload(Boolean value) {
      toBuild.needsFieldReload = value;
      return this;
    }
    public CreatedByUserBuilder needsUserReload(Boolean value) {
      toBuild.needsUserReload = value;
      return this;
    }
    public CreatedByUserBuilder userId(Integer value) {
      toBuild.userId = value;
      return this;
    }
    public CreatedByUserBuilder userNotifications(List<UserNotification> value) {
      toBuild.userNotifications = value;
      return this;
    }
    public CreatedByUserBuilder username(String value) {
      toBuild.username = value;
      return this;
    }
  }
}
