/**
 * File generated by Magnet rest2mobile 1.1 - Nov 20, 2015 7:41:04 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;
import java.util.List;

public interface UserWithImages {

  /**
   * Generated from URL GET http://localhost:8080/Fut5-war/webservice/getUserWithImage
   * GET Fut5-war/webservice/getUserWithImage
   * @param listener
   * @return List<UsersWithImagesResult>
   */
  Call<List<UsersWithImagesResult>> getusersWithImages(StateChangedListener listener);
}
