/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "id" : 3441575,
  "name" : "Montevideo",
  "coord" : {
    "lon" : -56.167351,
    "lat" : -34.833462
  },
  "country" : "UY",
  "population" : 0,
  "sys" : {
    "population" : 0
  }
}

 */

public class City {

  
  private Coord coord;

  
  private String country;

  
  private Integer id;

  
  private String name;

  
  private Integer population;

  
  private Sys sys;

  public Coord getCoord() {
    return coord;
  }
  public String getCountry() {
    return country;
  }
  public Integer getId() {
    return id;
  }
  public String getName() {
    return name;
  }
  public Integer getPopulation() {
    return population;
  }
  public Sys getSys() {
    return sys;
  }

  /**
  * Builder for City
  **/
  public static class CityBuilder {
    private City toBuild = new City();

    public CityBuilder() {
    }

    public City build() {
      return toBuild;
    }

    public CityBuilder coord(Coord value) {
      toBuild.coord = value;
      return this;
    }
    public CityBuilder country(String value) {
      toBuild.country = value;
      return this;
    }
    public CityBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public CityBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
    public CityBuilder population(Integer value) {
      toBuild.population = value;
      return this;
    }
    public CityBuilder sys(Sys value) {
      toBuild.sys = value;
      return this;
    }
  }
}
