/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "all" : 80
}

 */

public class Clouds {

  
  private Integer all;

  public Integer getAll() {
    return all;
  }

  /**
  * Builder for Clouds
  **/
  public static class CloudsBuilder {
    private Clouds toBuild = new Clouds();

    public CloudsBuilder() {
    }

    public Clouds build() {
      return toBuild;
    }

    public CloudsBuilder all(Integer value) {
      toBuild.all = value;
      return this;
    }
  }
}
