/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "lon" : -56.167351,
  "lat" : -34.833462
}

 */

public class Coord {

  
  private Double lat;

  
  private Double lon;

  public Double getLat() {
    return lat;
  }
  public Double getLon() {
    return lon;
  }

  /**
  * Builder for Coord
  **/
  public static class CoordBuilder {
    private Coord toBuild = new Coord();

    public CoordBuilder() {
    }

    public Coord build() {
      return toBuild;
    }

    public CoordBuilder lat(Double value) {
      toBuild.lat = value;
      return this;
    }
    public CoordBuilder lon(Double value) {
      toBuild.lon = value;
      return this;
    }
  }
}
