/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "temp" : 22.38,
  "temp_min" : 21.96,
  "temp_max" : 22.38,
  "pressure" : 1010.42,
  "sea_level" : 1012.63,
  "grnd_level" : 1010.42,
  "humidity" : 95,
  "temp_kf" : 0.42
}

 */

public class Main {

  
  private Double grnd_level;

  
  private Integer humidity;

  
  private Double pressure;

  
  private Double sea_level;

  
  private Double temp;

  
  private Double temp_kf;

  
  private Double temp_max;

  
  private Double temp_min;

  public Double getGrnd_level() {
    return grnd_level;
  }
  public Integer getHumidity() {
    return humidity;
  }
  public Double getPressure() {
    return pressure;
  }
  public Double getSea_level() {
    return sea_level;
  }
  public Double getTemp() {
    return temp;
  }
  public Double getTemp_kf() {
    return temp_kf;
  }
  public Double getTemp_max() {
    return temp_max;
  }
  public Double getTemp_min() {
    return temp_min;
  }

  /**
  * Builder for Main
  **/
  public static class MainBuilder {
    private Main toBuild = new Main();

    public MainBuilder() {
    }

    public Main build() {
      return toBuild;
    }

    public MainBuilder grnd_level(Double value) {
      toBuild.grnd_level = value;
      return this;
    }
    public MainBuilder humidity(Integer value) {
      toBuild.humidity = value;
      return this;
    }
    public MainBuilder pressure(Double value) {
      toBuild.pressure = value;
      return this;
    }
    public MainBuilder sea_level(Double value) {
      toBuild.sea_level = value;
      return this;
    }
    public MainBuilder temp(Double value) {
      toBuild.temp = value;
      return this;
    }
    public MainBuilder temp_kf(Double value) {
      toBuild.temp_kf = value;
      return this;
    }
    public MainBuilder temp_max(Double value) {
      toBuild.temp_max = value;
      return this;
    }
    public MainBuilder temp_min(Double value) {
      toBuild.temp_min = value;
      return this;
    }
  }
}
