/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "id" : 500,
  "main" : "Rain",
  "description" : "lightrain",
  "icon" : "10d"
}

 */

public class Weather {

  
  private String description;

  
  private String icon;

  
  private Integer id;

  
  private String main;

  public String getDescription() {
    return description;
  }
  public String getIcon() {
    return icon;
  }
  public Integer getId() {
    return id;
  }
  public String getMain() {
    return main;
  }

  /**
  * Builder for Weather
  **/
  public static class WeatherBuilder {
    private Weather toBuild = new Weather();

    public WeatherBuilder() {
    }

    public Weather build() {
      return toBuild;
    }

    public WeatherBuilder description(String value) {
      toBuild.description = value;
      return this;
    }
    public WeatherBuilder icon(String value) {
      toBuild.icon = value;
      return this;
    }
    public WeatherBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public WeatherBuilder main(String value) {
      toBuild.main = value;
      return this;
    }
  }
}
