/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 6:34:55 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.model.beans;


/**
 * Generated from json example
{
  "speed" : 1.97,
  "deg" : 335.001
}

 */

public class Wind {

  
  private Double deg;

  
  private Double speed;

  public Double getDeg() {
    return deg;
  }
  public Double getSpeed() {
    return speed;
  }

  /**
  * Builder for Wind
  **/
  public static class WindBuilder {
    private Wind toBuild = new Wind();

    public WindBuilder() {
    }

    public Wind build() {
      return toBuild;
    }

    public WindBuilder deg(Double value) {
      toBuild.deg = value;
      return this;
    }
    public WindBuilder speed(Double value) {
      toBuild.speed = value;
      return this;
    }
  }
}
