/**
 * File generated by Magnet rest2mobile 1.1 - Nov 22, 2015 7:40:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;

public interface UserUpdate {

  /**
   * Generated from URL POST http://localhost:8080/Fut5-war/webservice/updateUser?userId=546545&username=juanma&password=juanma&firstName=Juan+Martin&lastName=Gallo&email=juanmartingallo93%40gmail.com
   * POST Fut5-war/webservice/updateUser
   * @param userId  style:QUERY
   * @param username  style:QUERY
   * @param password  style:QUERY
   * @param firstName  style:QUERY
   * @param lastName  style:QUERY
   * @param email  style:QUERY
   * @param body  style:PLAIN
   * @param listener
   * @return String
   */
  Call<String> updateUser(
     String userId,
     String username,
     String password,
     String firstName,
     String lastName,
     String email,
     UpdateUserRequest body,
     StateChangedListener listener
  );


}
