/**
 * File generated by Magnet rest2mobile 1.1 - Nov 22, 2015 7:40:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ort.num172159_180968.fut5.model.beans.*;

public class UserUpdateFactory extends ControllerFactory<UserUpdate> {
  public UserUpdateFactory(MagnetMobileClient magnetClient) {
    super(UserUpdate.class, UserUpdateSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller UserUpdate
  public static class UserUpdateSchemaFactory extends AbstractControllerSchemaFactory {
    private static UserUpdateSchemaFactory __instance;

    public static synchronized UserUpdateSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new UserUpdateSchemaFactory();
      }

      return __instance;
    }

    private UserUpdateSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method updateUser
      JMethod method1 = addMethod("updateUser",
        "Fut5-war/webservice/updateUser",
        "POST",
        String.class,
        null,
        Arrays.asList("application/json"),
        Arrays.asList("text/plain"));
      method1.setBaseUrl("http://localhost:8080");
      method1.addParam("userId",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("username",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("password",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("firstName",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("lastName",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("email",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("body",
        "PLAIN",
        UpdateUserRequest.class,
        null,
        "",
        true);
    }

  }

}
