/**
 * File generated by Magnet rest2mobile 1.1 - Nov 26, 2015 7:48:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ort.num172159_180968.fut5.model.beans.*;
import java.util.List;

public class UserNotificationFactory extends ControllerFactory<UserNotification> {
  public UserNotificationFactory(MagnetMobileClient magnetClient) {
    super(UserNotification.class, UserNotificationSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller UserNotification
  public static class UserNotificationSchemaFactory extends AbstractControllerSchemaFactory {
    private static UserNotificationSchemaFactory __instance;

    public static synchronized UserNotificationSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new UserNotificationSchemaFactory();
      }

      return __instance;
    }

    private UserNotificationSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getNotifications
      JMethod method1 = addMethod("getNotifications",
        "Fut5-war/webservice/getNotifications",
        "GET",
        List.class,
        NotificationsResult.class,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://localhost:8080");
      method1.addParam("username",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
