/**
 * File generated by Magnet rest2mobile 1.1 - Nov 18, 2015 9:22:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;

public interface Image {

  /**
   * Generated from URL POST http://192.168.1.105:8080/Fut5-war/webservice/addUserImage?username=juan
   * POST Fut5-war/webservice/addUserImage
   * @param username  style:QUERY
   * @param body  style:PLAIN
   * @param listener
   * @return String
   */
  Call<String> addUserImage(
     String username,
     AddUserImageRequest body,
     StateChangedListener listener
  );


}
