/**
 * File generated by Magnet rest2mobile 1.1 - Nov 18, 2015 9:22:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ort.num172159_180968.fut5.model.beans.*;

public class ImageFactory extends ControllerFactory<Image> {
  public ImageFactory(MagnetMobileClient magnetClient) {
    super(Image.class, ImageSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller Image
  public static class ImageSchemaFactory extends AbstractControllerSchemaFactory {
    private static ImageSchemaFactory __instance;

    public static synchronized ImageSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new ImageSchemaFactory();
      }

      return __instance;
    }

    private ImageSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method addUserImage
      JMethod method1 = addMethod("addUserImage",
        "Fut5-war/webservice/addUserImage",
        "POST",
        String.class,
        null,
        Arrays.asList("application/json"),
        Arrays.asList("text/plain"));
      method1.setBaseUrl("http://192.168.1.105:8080");
      method1.addParam("username",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("body",
        "PLAIN",
        AddUserImageRequest.class,
        null,
        "",
        true);
    }

  }

}
