/**
 * File generated by Magnet rest2mobile 1.1 - Nov 18, 2015 9:22:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.controller.api.Image;
import com.ort.num172159_180968.fut5.controller.api.ImageFactory;
import com.ort.num172159_180968.fut5.model.beans.*;

/**
* This is generated stub to test {@link Image}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class ImageTest extends InstrumentationTestCase {
  private Image image;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    ImageFactory controllerFactory = new ImageFactory(magnetClient);
    image = controllerFactory.obtainInstance();

    assertNotNull(image);
  }

  /**
    * Generated unit test for {@link Image#addUserImage}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testAddUserImage() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String username = null;
    AddUserImageRequest body = null;

    Call<String> callObject = image.addUserImage(
      username, 
      body, null);
    assertNotNull(callObject);

    String result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
