/**
 * File generated by Magnet rest2mobile 1.1 - Oct 12, 2015 11:30:44 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.controller.api.Fields;
import com.ort.num172159_180968.fut5.controller.api.FieldsFactory;
import com.ort.num172159_180968.fut5.model.beans.*;
import java.util.List;

/**
* This is generated stub to test {@link Fields}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class FieldsTest extends InstrumentationTestCase {
  private Fields fields;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    FieldsFactory controllerFactory = new FieldsFactory(magnetClient);
    fields = controllerFactory.obtainInstance();

    assertNotNull(fields);
  }

  /**
    * Generated unit test for {@link Fields#getFields}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetFields() throws SchemaException, ExecutionException, InterruptedException {
    Call<List<FieldsResult>> callObject = fields.getFields(null);
    assertNotNull(callObject);

    List<FieldsResult> result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
