/**
 * File generated by Magnet rest2mobile 1.1 - Dec 15, 2015 12:47:13 AM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.controller.api.StatisticsTest;
import com.ort.num172159_180968.fut5.controller.api.StatisticsTestFactory;
import com.ort.num172159_180968.fut5.model.beans.*;

/**
* This is generated stub to test {@link StatisticsTest}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class StatisticsTestTest extends InstrumentationTestCase {
  private StatisticsTest statisticsTest;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    StatisticsTestFactory controllerFactory = new StatisticsTestFactory(magnetClient);
    statisticsTest = controllerFactory.obtainInstance();

    assertNotNull(statisticsTest);
  }

  /**
    * Generated unit test for {@link StatisticsTest#getPlayerStatistics}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetPlayerStatistics() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String username = null;

    Call<PlayerStatisticsResult> callObject = statisticsTest.getPlayerStatistics(
      username, null);
    assertNotNull(callObject);

    PlayerStatisticsResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
