/**
 * File generated by Magnet rest2mobile 1.1 - Dec 13, 2015 1:08:05 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.controller.api.Statistic;
import com.ort.num172159_180968.fut5.controller.api.StatisticFactory;
import com.ort.num172159_180968.fut5.model.beans.*;

/**
* This is generated stub to test {@link Statistic}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class StatisticTest extends InstrumentationTestCase {
  private Statistic statistic;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    StatisticFactory controllerFactory = new StatisticFactory(magnetClient);
    statistic = controllerFactory.obtainInstance();

    assertNotNull(statistic);
  }

  /**
    * Generated unit test for {@link Statistic#saveMatchGoals}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testSaveMatchGoals() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String idMatch = null;
    String localGoals = null;
    String visitorGoals = null;

    Call<SaveMatchGoalsResult> callObject = statistic.saveMatchGoals(
      idMatch, 
      localGoals, 
      visitorGoals, null);
    assertNotNull(callObject);

    SaveMatchGoalsResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
