/**
 * File generated by Magnet rest2mobile 1.1 - Nov 22, 2015 7:40:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.controller.api.UserUpdate;
import com.ort.num172159_180968.fut5.controller.api.UserUpdateFactory;
import com.ort.num172159_180968.fut5.model.beans.*;

/**
* This is generated stub to test {@link UserUpdate}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class UserUpdateTest extends InstrumentationTestCase {
  private UserUpdate userUpdate;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    UserUpdateFactory controllerFactory = new UserUpdateFactory(magnetClient);
    userUpdate = controllerFactory.obtainInstance();

    assertNotNull(userUpdate);
  }

  /**
    * Generated unit test for {@link UserUpdate#updateUser}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testUpdateUser() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String userId = null;
    String username = null;
    String password = null;
    String firstName = null;
    String lastName = null;
    String email = null;
    UpdateUserRequest body = null;

    Call<String> callObject = userUpdate.updateUser(
      userId, 
      username, 
      password, 
      firstName, 
      lastName, 
      email, 
      body, null);
    assertNotNull(callObject);

    String result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
