/**
 * File generated by Magnet rest2mobile 1.1 - Oct 14, 2015 8:04:39 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.controller.api.User;
import com.ort.num172159_180968.fut5.controller.api.UserFactory;
import com.ort.num172159_180968.fut5.model.beans.AddUserResult;

/**
* This is generated stub to test {@link User}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class UserTest extends InstrumentationTestCase {
  private User user;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    UserFactory controllerFactory = new UserFactory(magnetClient);
    user = controllerFactory.obtainInstance();

    assertNotNull(user);
  }

  /**
    * Generated unit test for {@link User#addUser}
    */
  @SmallTest
  public void testAddUser() throws SchemaException, ExecutionException, InterruptedException {

    String username = "juan";
    String password = "juan";
    String firstName = "juan";
    String lastName = "juan";
    String email = "juan";
    String url = null;

    Call<AddUserResult> callObject = user.addUser(
      username, 
      password, 
      firstName, 
      lastName, 
      email, 
      url, null);
    assertNotNull(callObject);

    AddUserResult result = callObject.get();
    
    //TODO : add more asserts
  }

}
