/**
 * File generated by Magnet rest2mobile 1.1 - Nov 20, 2015 7:41:04 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.model.beans.*;
import java.util.List;

/**
* This is generated stub to test {@link UserWithImages}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class UserWithImagesTest extends InstrumentationTestCase {
  private UserWithImages userWithImages;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    UserWithImagesFactory controllerFactory = new UserWithImagesFactory(magnetClient);
    userWithImages = controllerFactory.obtainInstance();

    assertNotNull(userWithImages);
  }

  /**
    * Generated unit test for {@link UserWithImages#getusersWithImages}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetusersWithImages() throws SchemaException, ExecutionException, InterruptedException {
    Call<List<UsersWithImagesResult>> callObject = userWithImages.getusersWithImages(null);
    assertNotNull(callObject);

    List<UsersWithImagesResult> result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
