/**
 * File generated by Magnet rest2mobile 1.1 - Oct 17, 2015 9:16:14 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ort.num172159_180968.fut5.controller.api.UserLogIn;
import com.ort.num172159_180968.fut5.controller.api.UserLogInFactory;

/**
* This is generated stub to test {@link UserLogIn}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class UserLogInTest extends InstrumentationTestCase {
  private UserLogIn userLogIn;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    UserLogInFactory controllerFactory = new UserLogInFactory(magnetClient);
    userLogIn = controllerFactory.obtainInstance();

    assertNotNull(userLogIn);
  }

  /**
    * Generated unit test for {@link UserLogIn#logIn}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testLogIn() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String username = null;
    String password = null;

    Call<String> callObject = userLogIn.logIn(
      username, 
      password, null);
    assertNotNull(callObject);

    String result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
