/**
 * File generated by Magnet rest2mobile 1.1 - Nov 27, 2015 7:57:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ort.num172159_180968.fut5.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ort.num172159_180968.fut5.model.beans.*;
import java.util.List;

public interface MatchTest {

  /**
   * Generated from URL GET http://localhost:8080/Fut5-war/webservice/getMatches?username=mika&mine=true&next=false
   * GET Fut5-war/webservice/getMatches
   * @param username  style:QUERY
   * @param mine  style:QUERY
   * @param next  style:QUERY
   * @param listener
   * @return List<MatchesResult>
   */
  Call<List<MatchesResult>> getMatches(
     String username,
     String mine,
     String next,
     StateChangedListener listener
  );


}
